grpc:
  port: 8088
  development: true

probes:
  readinessPath: /ready
  livenessPath: /live
  port: 3001
  pprof: 6001
  prometheusPath: /metrics
  prometheusPort: 8001
  checkIntervalSeconds: 10

db:
  host: postgres16
  port: 5432
  username: root
  password: mysecurepassword
  dbname: shop
  sslmode: disable
  timezone: "utc"
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

mongo:
  uri: "mongodb://localhost:27017"
  user: admin
  password: admin
  db: shop
mongo_collections:
  shop: orders
  
log:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true

server:
  port: 8080
  mode: "dev"

jaeger:
  enable: true
  service_name: es_service
  host_port: "localhost:6831"
  log_spans: false

event_store:
  connection_string: "esdb://localhost:2113?tls=false"

elastic_search:
  url: "http://localhost:9200"
  sniff: false
  gzip: true
  explain: true
  fetch_source: true
  version: true
  pretty: true

elastic_indexes:
  orders: "orders"

service_name: es_service